import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* 1. Changed to 'flex' (which defaults to row) */}
      <body className="min-h-screen flex">
        
        {/* 2. Sidebar sits on the left */}
        <Sidebar />

        {/* 3. Main content takes up remaining width (flex-1) */}
        <main className="flex-1 bg-slate-50">
          {children}
        </main>

      </body>
    </html>
  );
}